definitions:
  handler_error.HTTPError:
    description: Estrutura para representar erros na API. Contém a mensagem de erro
      e um código opcional. Pode ser expandida conforme necessário.
    properties:
      code:
        description: Código do erro HTTP
        type: integer
      message:
        description: Mensagem descritiva do erro
        type: string
    type: object
  model.Player:
    properties:
      balance:
        type: integer
      email:
        type: string
      id:
        type: string
    type: object
  model.SlotMachine:
    properties:
      balance:
        type: integer
      description:
        type: string
      id:
        type: string
      initial_balance:
        type: integer
      level:
        type: integer
      multiple_gain:
        type: integer
      permutations:
        items:
          items:
            type: string
          type: array
        type: array
      symbols:
        additionalProperties:
          type: string
        type: object
    type: object
  usecase.CreatePlayerRequest:
    properties:
      balance:
        type: integer
      email:
        type: string
      password:
        type: string
    type: object
  usecase.CreatePlayerResponse:
    properties:
      player:
        $ref: '#/definitions/model.Player'
    type: object
  usecase.CreateSlotMachineRequest:
    properties:
      balance:
        type: integer
      description:
        type: string
      level:
        type: integer
      multiple_gain:
        type: integer
    type: object
  usecase.CreateSlotMachineResponse:
    properties:
      machine:
        $ref: '#/definitions/model.SlotMachine'
    type: object
  usecase.GetPlayerBalanceResponse:
    properties:
      player:
        $ref: '#/definitions/model.Player'
    type: object
  usecase.GetSlotMachineBalanceResponse:
    properties:
      machine:
        $ref: '#/definitions/model.SlotMachine'
    type: object
  usecase.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  usecase.LoginResponse:
    properties:
      token:
        type: string
    type: object
  usecase.PlayRequest:
    properties:
      amount_bet:
        type: integer
      machine_id:
        type: string
    type: object
  usecase.PlayResponse:
    properties:
      player_balance:
        type: integer
      result:
        items:
          type: string
        type: array
      slot_machine_balance:
        type: integer
      win:
        type: boolean
    type: object
info:
  contact: {}
  description: Esta API permite que jogadores interajam com máquinas de slot, consultem
    saldos, realizem apostas e autentiquem-se.
  termsOfService: http://swagger.io/terms/
  title: API Máquina de caça-níqueis
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Autentica um usuário e retorna um token JWT.
      parameters:
      - description: Dados de autenticação
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/usecase.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecase.LoginResponse'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "401":
          description: Credenciais inválidas
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
      summary: Login
      tags:
      - Authentication
  /machines:
    post:
      consumes:
      - application/json
      description: Permite a criação de uma nova máquina caça-níqueis com os parâmetros
        especificados.
      parameters:
      - description: Dados da máquina caça-níqueis a ser criada
        in: body
        name: createSlotMachineRequest
        required: true
        schema:
          $ref: '#/definitions/usecase.CreateSlotMachineRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Máquina criada com sucesso
          schema:
            $ref: '#/definitions/usecase.CreateSlotMachineResponse'
        "400":
          description: Payload inválido ou parâmetros inválidos
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
      security:
      - BearerAuth: []
      summary: Criar uma nova máquina caça-níqueis
      tags:
      - SlotMachine
  /machines/balance:
    get:
      consumes:
      - application/json
      description: Retorna o saldo da máquina caça-níqueis especificada.
      parameters:
      - description: ID da máquina caça-níqueis
        in: query
        name: machine_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Saldo da máquina caça-níqueis
          schema:
            $ref: '#/definitions/usecase.GetSlotMachineBalanceResponse'
        "400":
          description: ID da máquina caça-níqueis é obrigatório
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "401":
          description: Não autorizado
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "404":
          description: Máquina caça-níqueis não encontrada
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
      security:
      - BearerAuth: []
      summary: Obter saldo da máquina caça-níqueis
      tags:
      - SlotMachine
  /play:
    post:
      consumes:
      - application/json
      description: Permite que o jogador faça uma aposta e jogue na máquina caça-níqueis
        especificada.
      parameters:
      - description: Dados da jogada
        in: body
        name: playRequest
        required: true
        schema:
          $ref: '#/definitions/usecase.PlayRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Jogada realizada com sucesso
          schema:
            $ref: '#/definitions/usecase.PlayResponse'
        "400":
          description: Payload inválido
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "404":
          description: Máquina caça-níqueis não encontrada
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "422":
          description: Saldo insuficiente
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
      security:
      - BearerAuth: []
      summary: Jogar na máquina caça-níqueis
      tags:
      - SlotMachine
  /players:
    post:
      consumes:
      - application/json
      description: Permite a criação de um novo jogador com um saldo inicial.
      parameters:
      - description: Dados do jogador a ser criado
        in: body
        name: createPlayerRequest
        required: true
        schema:
          $ref: '#/definitions/usecase.CreatePlayerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Jogador criado com sucesso
          schema:
            $ref: '#/definitions/usecase.CreatePlayerResponse'
        "400":
          description: Payload inválido
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "409":
          description: Jogador já existe
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
      summary: Criar um novo jogador
      tags:
      - Player
  /players/balance:
    get:
      consumes:
      - application/json
      description: Retorna o saldo do jogador especificado.
      produces:
      - application/json
      responses:
        "200":
          description: Saldo do jogador
          schema:
            $ref: '#/definitions/usecase.GetPlayerBalanceResponse'
        "401":
          description: Não autorizado
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "404":
          description: Jogador não encontrado
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/handler_error.HTTPError'
      security:
      - BearerAuth: []
      summary: Obter saldo do jogador
      tags:
      - Player
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
